// import '../../../vendor/javascripts/waypoints.min.js'
import '../../../vendor/javascripts/jquery.counterup.min.js'
import '../../../vendor/javascripts/wow.min.js'
import '../../../vendor/javascripts/apexcharts.js'
import '../../../vendor/javascripts/slick.min.js'
import '../../../vendor/javascripts/select2.min.js'
import '../../../vendor/javascripts/owl.carousel.min.js'
import '../../../vendor/javascripts/jquery.magnific-popup.min.js'
import '../../../vendor/javascripts/custom.js'